-- MySQL Script generated by MySQL Workbench
-- 11/30/16 10:22:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gears
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gears` ;

-- -----------------------------------------------------
-- Schema gears
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gears` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `gears` ;

-- -----------------------------------------------------
-- Table `state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `state` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `state` (
  `state_code` INT NOT NULL,
  `state_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`state_code`));

SHOW WARNINGS;
CREATE UNIQUE INDEX `state_name_UNIQUE` ON `state` (`state_name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employee` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `employee` (
  `emp_id` INT NOT NULL AUTO_INCREMENT,
  `phone_number` VARCHAR(200) NULL,
  `first_name` VARCHAR(200) NOT NULL,
  `last_name` VARCHAR(200) NOT NULL,
  `emp_code` VARCHAR(100) NOT NULL,
  `is_manager` TINYINT(1) NOT NULL DEFAULT 0,
  `state` INT NOT NULL,
  PRIMARY KEY (`emp_id`),
  CONSTRAINT `fk_Employee_state`
  FOREIGN KEY (`state`)
  REFERENCES `state` (`state_code`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

SHOW WARNINGS;
CREATE UNIQUE INDEX `emp_code_UNIQUE` ON `employee` (`emp_code` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Employee_state_idx` ON `employee` (`state` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(200) NOT NULL,
  `last_name` VARCHAR(200) NOT NULL,
  `phone_number` VARCHAR(200) NOT NULL,
  `customer_zip` VARCHAR(50) NULL,
  PRIMARY KEY (`customer_id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `conventionvehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conventionvehicle` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `conventionvehicle` (
  `vehicle_id` INT NOT NULL AUTO_INCREMENT,
  `is_auto_trans` TINYINT(1) NOT NULL DEFAULT 1,
  `is_all_wheel` TINYINT(1) NOT NULL DEFAULT 0,
  `make` VARCHAR(100) NOT NULL,
  `year` INT NOT NULL,
  `trim` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`vehicle_id`))
  ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `customervehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `customervehicle` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `customervehicle` (
  `customer_vehicle_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `convention_vehicle_id` INT NOT NULL,
  `mileage` INT NOT NULL DEFAULT 0,
  `vin` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`customer_vehicle_id`),
  CONSTRAINT `fk_customer_vehicle_customer1`
  FOREIGN KEY (`customer_id`)
  REFERENCES `customer` (`customer_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_customer_vehicle_convention_vehicle1`
  FOREIGN KEY (`convention_vehicle_id`)
  REFERENCES `conventionvehicle` (`vehicle_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
  ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_customer_vehicle_customer1_idx` ON `customervehicle` (`customer_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_customer_vehicle_convention_vehicle1_idx` ON `customervehicle` (`convention_vehicle_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `unique_customer_vehicle_convention_vehicle_customer_id_idx` ON `customervehicle` (`customer_id` ASC, `convention_vehicle_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `vin_UNIQUE` ON `customervehicle` (`vin` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appointment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `appointment` (
  `appointment_id` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(512) NOT NULL,
  `update_time` DATETIME NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `description` VARCHAR(2048) NULL,
  `event_time` DATETIME NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `customer_id` INT NOT NULL,
  `state` INT NOT NULL,
  PRIMARY KEY (`appointment_id`),
  CONSTRAINT `fk_appointment_customer1`
  FOREIGN KEY (`customer_id`)
  REFERENCES `customer` (`customer_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_appointment_state1`
  FOREIGN KEY (`state`)
  REFERENCES `state` (`state_code`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

SHOW WARNINGS;
CREATE INDEX `fk_appointment_customer1_idx` ON `appointment` (`customer_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_appointment_state1_idx` ON `appointment` (`state` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `job` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `job` (
  `job_id` INT NOT NULL AUTO_INCREMENT,
  `job_key` VARCHAR(30) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `summary` VARCHAR(512) NOT NULL,
  `description` VARCHAR(2048) NULL,
  `state` INT NOT NULL,
  `appointment_id` INT NOT NULL,
  `mechanic_id` INT NOT NULL,
  `customer_vehicle_id` INT NOT NULL,
  PRIMARY KEY (`job_id`),
  CONSTRAINT `fk_job_state1`
  FOREIGN KEY (`state`)
  REFERENCES `state` (`state_code`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_job_appointment1`
  FOREIGN KEY (`appointment_id`)
  REFERENCES `appointment` (`appointment_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_job_Employee1`
  FOREIGN KEY (`mechanic_id`)
  REFERENCES `employee` (`emp_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_job_customer_vehicle1`
  FOREIGN KEY (`customer_vehicle_id`)
  REFERENCES `customervehicle` (`customer_vehicle_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

SHOW WARNINGS;
CREATE UNIQUE INDEX `job_key_UNIQUE` ON `job` (`job_key` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_job_state1_idx` ON `job` (`state` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_job_appointment1_idx` ON `job` (`appointment_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_job_Employee1_idx` ON `job` (`mechanic_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_job_customer_vehicle1_idx` ON `job` (`customer_vehicle_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `worksheet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worksheet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `worksheet` (
  `job_id` INT NOT NULL,
  `vehicle_mileage` INT NULL,
  `end_time` DATETIME NULL,
  `start_time` DATETIME NULL,
  PRIMARY KEY (`job_id`),
  CONSTRAINT `fk_worksheet_job1`
  FOREIGN KEY (`job_id`)
  REFERENCES `job` (`job_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
  ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `inventoryitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventoryitem` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `inventoryitem` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `convention_vehicle_id` INT NOT NULL,
  `item_code` VARCHAR(200) NOT NULL,
  `part_name` VARCHAR(200) NOT NULL,
  `category` VARCHAR(45) NOT NULL DEFAULT 'PARTS' COMMENT 'PARTS or LABOR',
  `unit` VARCHAR(45) NOT NULL,
  `unit_price` REAL NOT NULL DEFAULT 0,
  PRIMARY KEY (`item_id`),
  CONSTRAINT `fk_inventory_convention_vehicle1`
  FOREIGN KEY (`convention_vehicle_id`)
  REFERENCES `conventionvehicle` (`vehicle_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
  ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_inventory_convention_vehicle1_idx` ON `inventoryitem` (`convention_vehicle_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `unique_inventory_item_vechicle_item_code_idx` ON `inventoryitem` (`item_code` ASC, `convention_vehicle_id` ASC);

SHOW WARNINGS;
CREATE INDEX `index_inventory_item_code_name_idx` ON `inventoryitem` (`part_name` ASC, `item_code` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `task` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `task` (
  `inventory_item_id` INT NOT NULL,
  `worksheet_job_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `is_done` TINYINT(1) NOT NULL DEFAULT 0,
  `finish_time` DATETIME NULL,
  `amount_cost` REAL NOT NULL,
  PRIMARY KEY (`inventory_item_id`, `worksheet_job_id`),
  CONSTRAINT `fk_task_inventory_item1`
  FOREIGN KEY (`inventory_item_id`)
  REFERENCES `inventoryitem` (`item_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_task_worksheet1`
  FOREIGN KEY (`worksheet_job_id`)
  REFERENCES `worksheet` (`job_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
  ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_task_worksheet1_idx` ON `task` (`worksheet_job_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_task_inventory_item_idx` ON `task` (`inventory_item_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invoice` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `invoice` (
  `invoice_id` INT NOT NULL AUTO_INCREMENT,
  `appointment_id` INT NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL,
  `state` INT NOT NULL,
  `tax_rate` REAL NULL,
  `amount_due` REAL NULL,
  `amount_payed` REAL NULL,
  `discount_rate` REAL NULL,
  PRIMARY KEY (`invoice_id`),
  CONSTRAINT `fk_invoice_appointment1`
  FOREIGN KEY (`appointment_id`)
  REFERENCES `appointment` (`appointment_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_invoice_state1`
  FOREIGN KEY (`state`)
  REFERENCES `state` (`state_code`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

SHOW WARNINGS;
CREATE INDEX `fk_invoice_appointment1_idx` ON `invoice` (`appointment_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_invoice_state1_idx` ON `invoice` (`state` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
